# Generated by Django 4.1 on 2022-08-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=999)),
                ('precio', models.IntegerField()),
                ('fecha_actualizacion', models.DateField()),
            ],
        ),
    ]
