# Generated by Django 4.1 on 2022-08-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.CharField(max_length=999),
        ),
    ]
