# Generated by Django 4.1 on 2022-08-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_alter_producto_fecha_actualizacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='fecha_actualizacion',
            new_name='fecha',
        ),
    ]
